### ISSUE TITLE
isqrt algorithm

### ISSUE THREAD

**Issue by TuomLarsen** [leovt/constructible#8]
`isqrt` [mentions](https://github.com/leovt/constructible/blob/fb2ce56fb03de2914d4835e1af47533f58860d5c/constructible.py#L51) the need for more efficient implementation. Do you have anything in mind? Isn't the problem equivalent to integer factorization?

**Comment by leovt** [comment]
Yes it is essentially integer factirization which I did by trial division.

It should be possible to produce the result while factoring without building a complete factorized representation.

**Comment by TuomLarsen** [comment]
Thanks for the reply! In that case, I'm closing this.

**Comment by TuomLarsen** [comment]
May I ask you why are you using `fsqrt` at all? Why is it not sufficient to check whether `floor(sqrt(q.numerator)) ** 2 == q.numerator and floor(sqrt(q.denominator)) ** 2 == q.denominator`?
